trigger:
  - main

pool:
  name: 'Linode'

resources:
  repositories:
    - repository: templates
      name: BuildTemplates/templates
      type: git

variables:
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm/packages

stages:
  - stage: Format
    jobs:
      - job: Dprint
        steps:
          - template: dprint-format.yml@templates
            parameters:
              npmToken: $(GITLAB_NPM_TOKEN)
              nodeVersion: '20.x'
              cachePath: ${{ variables.npm_config_cache }}

  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            displayName: Install DotNet Core
            inputs:
              packageType: 'sdk'
              useGlobalJson: true
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Build Solution
            inputs:
              command: 'build'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: IntegrationTests
        displayName: Integration Tests
        steps:
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies' # 'testAssemblies' | 'testPlan' | 'testRun'. Required. Select tests using. Default: testAssemblies.
              testAssemblyVer2: # string. Required when testSelector = testAssemblies. Test files. 
              #testPlan: # string. Required when testSelector = testPlan. Test plan. 
              #testSuite: # string. Required when testSelector = testPlan. Test suite. 
              #testConfiguration: # string. Required when testSelector = testPlan. Test configuration. 
              #tcmTestRun: '$(test.RunId)' # string. Optional. Use when testSelector = testRun. Test Run. Default: $(test.RunId).
              searchFolder: '$(System.DefaultWorkingDirectory)' # string. Required. Search folder. Default: $(System.DefaultWorkingDirectory).
              #resultsFolder: '$(Agent.TempDirectory)\TestResults' # string. Test results folder. Default: $(Agent.TempDirectory)\TestResults.
              #testFiltercriteria: # string. Optional. Use when testSelector = testAssemblies. Test filter criteria. 
              #runOnlyImpactedTests: False # boolean. Optional. Use when testSelector = testAssemblies. Run only impacted tests. Default: False.
              #runAllTestsAfterXBuilds: '50' # string. Optional. Use when testSelector = testAssemblies && runOnlyImpactedTests = true. Number of builds after which all tests should be run. Default: 50.
              #uiTests: false # boolean. Test mix contains UI tests. Default: false.
              # Execution options
              #vstestLocationMethod: 'version' # 'version' | 'location'. Select test platform using. Default: version.
              #vsTestVersion: 'latest' # 'latest' | '17.0' | '16.0' | '15.0' | '14.0' | 'toolsInstaller'. Optional. Use when vstestLocationMethod = version. Test platform version. Default: latest.
              #vstestLocation: # string. Optional. Use when vstestLocationMethod = location. Path to vstest.console.exe. 
              #runSettingsFile: # string. Settings file. 
              #overrideTestrunParameters: # string. Override test run parameters. 
              #pathtoCustomTestAdapters: # string. Path to custom test adapters. 
              #runInParallel: False # boolean. Run tests in parallel on multi-core machines. Default: False.
              #runTestsInIsolation: False # boolean. Run tests in isolation. Default: False.
              #codeCoverageEnabled: False # boolean. Code coverage enabled. Default: False.
              #otherConsoleOptions: # string. Other console options. 
              #diagnosticsEnabled: false # boolean. Collect advanced diagnostics in case of catastrophic failures. Default: false.
              #collectDumpOn: 'onAbortOnly' # 'onAbortOnly' | 'always' | 'never'. Optional. Use when diagnosticsEnabled = true. Collect process dump and attach to test run report. Default: onAbortOnly.
              #rerunFailedTests: False # boolean. Rerun failed tests. Default: False.
              #rerunType: 'basedOnTestFailurePercentage' # 'basedOnTestFailurePercentage' | 'basedOnTestFailureCount'. Optional. Use when rerunFailedTests = true. Do not rerun if test failures exceed specified threshold. Default: basedOnTestFailurePercentage.
              #rerunFailedThreshold: '30' # string. Optional. Use when rerunFailedTests = true && rerunType = basedOnTestFailurePercentage. % failure. Default: 30.
              #rerunFailedTestCasesMaxLimit: '5' # string. Optional. Use when rerunFailedTests = true && rerunType = basedOnTestFailureCount. # of failed tests. Default: 5.
              #rerunMaxAttempts: '3' # string. Optional. Use when rerunFailedTests = true. Maximum # of attempts. Default: 3.
              # Advanced execution options
              #distributionBatchType: 'basedOnTestCases' # 'basedOnTestCases' | 'basedOnExecutionTime' | 'basedOnAssembly'. Batch tests. Default: basedOnTestCases.
              #batchingBasedOnAgentsOption: 'autoBatchSize' # 'autoBatchSize' | 'customBatchSize'. Optional. Use when distributionBatchType = basedOnTestCases. Batch options. Default: autoBatchSize.
              #customBatchSizeValue: '10' # string. Required when distributionBatchType = basedOnTestCases && batchingBasedOnAgentsOption = customBatchSize. Number of tests per batch. Default: 10.
              #batchingBasedOnExecutionTimeOption: 'autoBatchSize' # 'autoBatchSize' | 'customTimeBatchSize'. Optional. Use when distributionBatchType = basedOnExecutionTime. Batch options. Default: autoBatchSize.
              #customRunTimePerBatchValue: '60' # string. Required when distributionBatchType = basedOnExecutionTime && batchingBasedOnExecutionTimeOption = customTimeBatchSize. Running time (sec) per batch. Default: 60.
              #dontDistribute: False # boolean. Replicate tests instead of distributing when multiple agents are used in the job. Default: False.
              # Reporting options
              #testRunTitle: # string. Test run title. 
              #platform: # string. Build platform. 
              #configuration: # string. Build configuration. 
              #publishRunAttachments: true # boolean. Upload test attachments. Default: true.
              #failOnMinTestsNotRun: False # boolean. Fail the task if a minimum number of tests are not run. Default: False.
              #minimumExpectedTests: '1' # string. Optional. Use when failOnMinTestsNotRun = true. Minimum # of tests. Default: 1.

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - stage: Publish
        jobs:
          - job: Publish
            steps:
              - task: UseDotNet@2
                displayName: Install DotNet Core
                inputs:
                  packageType: 'sdk'
                  useGlobalJson: true
                  includePreviewVersions: true
              - task: NuGetToolInstaller@1
                displayName: Install NuGet Tool
              - task: DotNetCoreCLI@2
                displayName: Restore Solution
                inputs:
                  command: 'restore'
              - task: DotNetCoreCLI@2
                displayName: Pack
                inputs:
                  command: pack
                  versioningScheme: byPrereleaseNumber
                  majorVersion: '1'
                  minorVersion: '0'
                  patchVersion: '0'
              - task: DotNetCoreCLI@2
                displayName: Push
                inputs:
                  command: 'push'
                  searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
                  feedPublish: 'stackworx'