// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stackworx.Hotchocolate.Muidatagrid.Entities;

#nullable disable

namespace Stackworx.Hotchocolate.MuiDataGrid.Migrations
{
    [DbContext(typeof(MuiDataGridDbContext))]
    [Migration("20220705102028_ApartmentSellDate")]
    partial class ApartmentSellDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetLine2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            Province = "Limpopo",
                            StreetLine1 = "Wroxham Road",
                            StreetLine2 = "",
                            StreetNumber = 0
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 2,
                            Province = "Gauteng",
                            StreetLine1 = "",
                            StreetLine2 = "",
                            StreetNumber = 0
                        });
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SellDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apartment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseNumber = 56,
                            Name = "House 1",
                            Price = 13.89m
                        },
                        new
                        {
                            Id = 2,
                            HouseNumber = 4,
                            Name = "House Number 2",
                            Price = 15.78m,
                            SellDate = new DateTime(2022, 7, 5, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6000)
                        });
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAtDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IdCardReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MarriageDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Married")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedAtDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Age = 18,
                            Bio = "I like water",
                            CreatedAtDate = new DateOnly(2022, 5, 31),
                            DateOfBirth = new DateTime(2022, 7, 5, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6570),
                            Firstname = "Johanny",
                            Gender = "MALE",
                            IdCardReceivedDate = new DateTime(2022, 7, 5, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6580),
                            Lastname = "Klein",
                            Married = false,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 31),
                            Weight = 100.0
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Age = 36,
                            Bio = "I like Chocolate",
                            CreatedAtDate = new DateOnly(2022, 5, 30),
                            DateOfBirth = new DateTime(2022, 7, 4, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6590),
                            Firstname = "Stacey",
                            Gender = "FEMALE",
                            IdCardReceivedDate = new DateTime(2022, 7, 4, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6600),
                            Lastname = "Pop",
                            Married = true,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 30),
                            Weight = 76.0
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            Age = 11,
                            Bio = "I like toys",
                            CreatedAtDate = new DateOnly(2022, 5, 29),
                            DateOfBirth = new DateTime(2022, 7, 3, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6600),
                            Firstname = "Susie",
                            Gender = "FEMALE",
                            IdCardReceivedDate = new DateTime(2022, 7, 3, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6610),
                            Lastname = "van zyl",
                            Married = false,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 29),
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            Age = 55,
                            Bio = "I like hunting",
                            CreatedAtDate = new DateOnly(2022, 5, 28),
                            DateOfBirth = new DateTime(2022, 7, 2, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6610),
                            Firstname = "Johan",
                            Gender = "MALE",
                            IdCardReceivedDate = new DateTime(2022, 7, 2, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6610),
                            Lastname = "Groot",
                            Married = true,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 28),
                            Weight = 112.0
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 2,
                            Age = 26,
                            Bio = "I like art",
                            CreatedAtDate = new DateOnly(2022, 5, 27),
                            DateOfBirth = new DateTime(2022, 7, 1, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6620),
                            Firstname = "Celeste",
                            Gender = "FEMALE",
                            IdCardReceivedDate = new DateTime(2022, 7, 1, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6620),
                            Lastname = "Le Roux",
                            Married = false,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 27),
                            Weight = 74.0
                        });
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Address", b =>
                {
                    b.HasOne("Stackworx.Hotchocolate.Muidatagrid.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Person", b =>
                {
                    b.HasOne("Stackworx.Hotchocolate.Muidatagrid.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
