// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stackworx.Hotchocolate.MuiDataGrid.Migrations
{
    public partial class AddressPrice : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "Price",
                table: "Apartment",
                type: "TEXT",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.UpdateData(
                table: "Apartment",
                keyColumn: "Id",
                keyValue: 1,
                column: "Price",
                value: 13.89m);

            migrationBuilder.UpdateData(
                table: "Apartment",
                keyColumn: "Id",
                keyValue: 2,
                column: "Price",
                value: 15.78m);

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 5, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(4990), new DateTime(2022, 7, 5, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5010) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 4, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5020), new DateTime(2022, 7, 4, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5030) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 3, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5030), new DateTime(2022, 7, 3, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5030) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 2, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5040), new DateTime(2022, 7, 2, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5040) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 1, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5050), new DateTime(2022, 7, 1, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5050) });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Price",
                table: "Apartment");

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 6, 23, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4720), new DateTime(2022, 6, 23, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4750) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 6, 22, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4750), new DateTime(2022, 6, 22, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4760) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 6, 21, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4760), new DateTime(2022, 6, 21, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4770) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 6, 20, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4770), new DateTime(2022, 6, 20, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4780) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 6, 19, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4780), new DateTime(2022, 6, 19, 12, 11, 11, 442, DateTimeKind.Local).AddTicks(4780) });
        }
    }
}
