// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stackworx.Hotchocolate.MuiDataGrid.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "People",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Firstname = table.Column<string>(type: "TEXT", nullable: false),
                    Lastname = table.Column<string>(type: "TEXT", nullable: false),
                    Bio = table.Column<string>(type: "TEXT", nullable: true),
                    Age = table.Column<int>(type: "INTEGER", nullable: false),
                    Married = table.Column<bool>(type: "INTEGER", nullable: false),
                    Gender = table.Column<string>(type: "TEXT", nullable: false),
                    Weight = table.Column<double>(type: "REAL", nullable: true),
                    RefId = table.Column<Guid>(type: "TEXT", nullable: false),
                    DateOfBirth = table.Column<DateTime>(type: "TEXT", nullable: false),
                    MarriageDate = table.Column<DateTimeOffset>(type: "TEXT", nullable: true),
                    IdCardReceivedDate = table.Column<DateTime>(type: "TEXT", nullable: true),
                    CreatedAtDate = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    UpdatedAtDate = table.Column<DateOnly>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_People", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "People",
                columns: new[] { "Id", "Age", "Bio", "CreatedAtDate", "DateOfBirth", "Firstname", "Gender", "IdCardReceivedDate", "Lastname", "MarriageDate", "Married", "RefId", "UpdatedAtDate", "Weight" },
                values: new object[] { 1, 18, "I like water", new DateOnly(2022, 5, 31), new DateTime(2022, 6, 2, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8250), "Johanny", "MALE", new DateTime(2022, 6, 2, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8280), "Klein", null, false, new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"), new DateOnly(2022, 5, 31), 100.0 });

            migrationBuilder.InsertData(
                table: "People",
                columns: new[] { "Id", "Age", "Bio", "CreatedAtDate", "DateOfBirth", "Firstname", "Gender", "IdCardReceivedDate", "Lastname", "MarriageDate", "Married", "RefId", "UpdatedAtDate", "Weight" },
                values: new object[] { 2, 36, "I like Chocolate", new DateOnly(2022, 5, 30), new DateTime(2022, 6, 1, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8280), "Stacey", "FEMALE", new DateTime(2022, 6, 1, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8290), "Pop", null, true, new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"), new DateOnly(2022, 5, 30), 76.0 });

            migrationBuilder.InsertData(
                table: "People",
                columns: new[] { "Id", "Age", "Bio", "CreatedAtDate", "DateOfBirth", "Firstname", "Gender", "IdCardReceivedDate", "Lastname", "MarriageDate", "Married", "RefId", "UpdatedAtDate", "Weight" },
                values: new object[] { 3, 11, "I like toys", new DateOnly(2022, 5, 29), new DateTime(2022, 5, 31, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8290), "Susie", "FEMALE", new DateTime(2022, 5, 31, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8300), "van zyl", null, false, new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"), new DateOnly(2022, 5, 29), 30.0 });

            migrationBuilder.InsertData(
                table: "People",
                columns: new[] { "Id", "Age", "Bio", "CreatedAtDate", "DateOfBirth", "Firstname", "Gender", "IdCardReceivedDate", "Lastname", "MarriageDate", "Married", "RefId", "UpdatedAtDate", "Weight" },
                values: new object[] { 4, 55, "I like hunting", new DateOnly(2022, 5, 28), new DateTime(2022, 5, 30, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8300), "Johan", "MALE", new DateTime(2022, 5, 30, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8310), "Groot", null, true, new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"), new DateOnly(2022, 5, 28), 112.0 });

            migrationBuilder.InsertData(
                table: "People",
                columns: new[] { "Id", "Age", "Bio", "CreatedAtDate", "DateOfBirth", "Firstname", "Gender", "IdCardReceivedDate", "Lastname", "MarriageDate", "Married", "RefId", "UpdatedAtDate", "Weight" },
                values: new object[] { 5, 26, "I like art", new DateOnly(2022, 5, 27), new DateTime(2022, 5, 29, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8310), "Celeste", "FEMALE", new DateTime(2022, 5, 29, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8310), "Le Roux", null, false, new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"), new DateOnly(2022, 5, 27), 74.0 });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "People");
        }
    }
}
