// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stackworx.Hotchocolate.Muidatagrid.Entities;

#nullable disable

namespace Stackworx.Hotchocolate.MuiDataGrid.Migrations
{
    [DbContext(typeof(MuiDataGridDbContext))]
    [Migration("20220602094926_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAtDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IdCardReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MarriageDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Married")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedAtDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 18,
                            Bio = "I like water",
                            CreatedAtDate = new DateOnly(2022, 5, 31),
                            DateOfBirth = new DateTime(2022, 6, 2, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8250),
                            Firstname = "Johanny",
                            Gender = "MALE",
                            IdCardReceivedDate = new DateTime(2022, 6, 2, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8280),
                            Lastname = "Klein",
                            Married = false,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 31),
                            Weight = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Age = 36,
                            Bio = "I like Chocolate",
                            CreatedAtDate = new DateOnly(2022, 5, 30),
                            DateOfBirth = new DateTime(2022, 6, 1, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8280),
                            Firstname = "Stacey",
                            Gender = "FEMALE",
                            IdCardReceivedDate = new DateTime(2022, 6, 1, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8290),
                            Lastname = "Pop",
                            Married = true,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 30),
                            Weight = 76.0
                        },
                        new
                        {
                            Id = 3,
                            Age = 11,
                            Bio = "I like toys",
                            CreatedAtDate = new DateOnly(2022, 5, 29),
                            DateOfBirth = new DateTime(2022, 5, 31, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8290),
                            Firstname = "Susie",
                            Gender = "FEMALE",
                            IdCardReceivedDate = new DateTime(2022, 5, 31, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8300),
                            Lastname = "van zyl",
                            Married = false,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 29),
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 4,
                            Age = 55,
                            Bio = "I like hunting",
                            CreatedAtDate = new DateOnly(2022, 5, 28),
                            DateOfBirth = new DateTime(2022, 5, 30, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8300),
                            Firstname = "Johan",
                            Gender = "MALE",
                            IdCardReceivedDate = new DateTime(2022, 5, 30, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8310),
                            Lastname = "Groot",
                            Married = true,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 28),
                            Weight = 112.0
                        },
                        new
                        {
                            Id = 5,
                            Age = 26,
                            Bio = "I like art",
                            CreatedAtDate = new DateOnly(2022, 5, 27),
                            DateOfBirth = new DateTime(2022, 5, 29, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8310),
                            Firstname = "Celeste",
                            Gender = "FEMALE",
                            IdCardReceivedDate = new DateTime(2022, 5, 29, 11, 49, 26, 811, DateTimeKind.Local).AddTicks(8310),
                            Lastname = "Le Roux",
                            Married = false,
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 27),
                            Weight = 74.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
