// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stackworx.Hotchocolate.MuiDataGrid.Migrations
{
    public partial class ApartmentSellDate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "SellDate",
                table: "Apartment",
                type: "TEXT",
                nullable: true);

            migrationBuilder.UpdateData(
                table: "Apartment",
                keyColumn: "Id",
                keyValue: 2,
                column: "SellDate",
                value: new DateTime(2022, 7, 5, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6000));

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 5, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6570), new DateTime(2022, 7, 5, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6580) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 4, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6590), new DateTime(2022, 7, 4, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6600) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 3, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6600), new DateTime(2022, 7, 3, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6610) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 2, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6610), new DateTime(2022, 7, 2, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6610) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 1, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6620), new DateTime(2022, 7, 1, 12, 20, 27, 930, DateTimeKind.Local).AddTicks(6620) });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SellDate",
                table: "Apartment");

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 5, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(4990), new DateTime(2022, 7, 5, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5010) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 4, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5020), new DateTime(2022, 7, 4, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5030) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 3, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5030), new DateTime(2022, 7, 3, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5030) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 2, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5040), new DateTime(2022, 7, 2, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5040) });

            migrationBuilder.UpdateData(
                table: "People",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "DateOfBirth", "IdCardReceivedDate" },
                values: new object[] { new DateTime(2022, 7, 1, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5050), new DateTime(2022, 7, 1, 9, 59, 41, 927, DateTimeKind.Local).AddTicks(5050) });
        }
    }
}
