// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stackworx.Hotchocolate.Muidatagrid.Entities;

#nullable disable

namespace Stackworx.Hotchocolate.MuiDataGrid.Migrations
{
    [DbContext(typeof(MuiDataGridDbContext))]
    partial class MuiDataGridDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetLine2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            Province = "Limpopo",
                            StreetLine1 = "Wroxham Road",
                            StreetLine2 = "",
                            StreetNumber = 0
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 2,
                            Province = "Gauteng",
                            StreetLine1 = "",
                            StreetLine2 = "",
                            StreetNumber = 0
                        });
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApartmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SellDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apartment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentType = "OwnedProperty",
                            HouseNumber = 56,
                            Name = "House 1",
                            Price = 13.89m
                        },
                        new
                        {
                            Id = 2,
                            ApartmentType = "RentalProperty",
                            HouseNumber = 4,
                            Name = "House Number 2",
                            Price = 15.78m,
                            SellDate = new DateTime(2023, 4, 20, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(8760)
                        });
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BankAccountBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAtDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IdCardReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MarriageDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Married")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NonGraphQlSerialisedId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RefIdNullable")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedAtDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Age = 18,
                            Bio = "I like water",
                            CreatedAtDate = new DateOnly(2022, 5, 31),
                            DateOfBirth = new DateTime(2023, 4, 20, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9370),
                            Firstname = "Johanny",
                            Gender = "Male",
                            IdCardReceivedDate = new DateTime(2023, 4, 20, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9380),
                            Lastname = "Klein",
                            Married = false,
                            NonGraphQlSerialisedId = new Guid("9f1ef691-2c5c-4bde-b0be-635bdd4e180c"),
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 31),
                            Weight = 100.0
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Age = 36,
                            BankAccountBalance = 200.90m,
                            Bio = "I like Chocolate",
                            CreatedAtDate = new DateOnly(2022, 5, 30),
                            DateOfBirth = new DateTime(2023, 4, 19, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9390),
                            Firstname = "Stacey",
                            Gender = "Female",
                            IdCardReceivedDate = new DateTime(2023, 4, 19, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9400),
                            Lastname = "Pop",
                            Married = true,
                            NonGraphQlSerialisedId = new Guid("9f1ef691-2c5c-4bde-b0be-635bdd4e180c"),
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 30),
                            Weight = 76.0
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            Age = 11,
                            BankAccountBalance = 1000000.90m,
                            Bio = "I like toys",
                            CreatedAtDate = new DateOnly(2022, 5, 29),
                            DateOfBirth = new DateTime(2023, 4, 18, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9400),
                            Firstname = "Susie",
                            Gender = "Female",
                            IdCardReceivedDate = new DateTime(2023, 4, 18, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9410),
                            Lastname = "van zyl",
                            Married = false,
                            NonGraphQlSerialisedId = new Guid("9f1ef691-2c5c-4bde-b0be-635bdd4e180c"),
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 29),
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            Age = 55,
                            Bio = "I like hunting",
                            CreatedAtDate = new DateOnly(2022, 5, 28),
                            DateOfBirth = new DateTime(2023, 4, 17, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9410),
                            Firstname = "Johan",
                            Gender = "Male",
                            IdCardReceivedDate = new DateTime(2023, 4, 17, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9420),
                            Lastname = "Groot",
                            Married = true,
                            NonGraphQlSerialisedId = new Guid("00000000-0000-0000-0000-000000000000"),
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180b"),
                            UpdatedAtDate = new DateOnly(2022, 5, 28),
                            Weight = 112.0
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 2,
                            Age = 26,
                            BankAccountBalance = 50.99m,
                            Bio = "I like art",
                            CreatedAtDate = new DateOnly(2022, 5, 27),
                            DateOfBirth = new DateTime(2023, 4, 16, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9420),
                            Firstname = "Celeste",
                            Gender = "Female",
                            IdCardReceivedDate = new DateTime(2023, 4, 16, 20, 52, 40, 577, DateTimeKind.Local).AddTicks(9430),
                            Lastname = "Le Roux",
                            Married = false,
                            NonGraphQlSerialisedId = new Guid("9f1ef691-2c5c-4bde-b0be-635bdd4e180c"),
                            RefId = new Guid("9f1ef691-2c4b-4bde-b0ac-635bdd4e180c"),
                            UpdatedAtDate = new DateOnly(2022, 5, 27),
                            Weight = 74.0
                        });
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Address", b =>
                {
                    b.HasOne("Stackworx.Hotchocolate.Muidatagrid.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Stackworx.Hotchocolate.Muidatagrid.Entities.Person", b =>
                {
                    b.HasOne("Stackworx.Hotchocolate.Muidatagrid.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
